### ISSUE TITLE
ValueError: Null layer: 'ikkekartlagtsjomaltomr'

### ISSUE THREAD

**Issue by MasHyke** [simbli/seacharts#1]
Hi,
I am trying to follow your usage recipe on the README, but with a different map from a different county. I am getting the following error:

```Processing 45 km^2 of Hydrography features from: Basisdata_3004_Fredrikstad_25833_Dybdedata_FGDB.gdb
Saved 336 Seabed0m geometries to shapefile in 0.4 seconds.
Saved 104 Seabed5m geometries to shapefile in 0.1 seconds.
Saved 71 Seabed10m geometries to shapefile in 0.1 seconds.
Saved 12 Seabed20m geometries to shapefile in 0.0 seconds.
Found 0 Seabed50m geometries.

Processing 45 km^2 of Topography features from: Basisdata_3004_Fredrikstad_25833_Dybdedata_FGDB.gdb
Saved 50 Land geometries to shapefile in 0.2 seconds.
Number of shore records read: 216Traceback (most recent call last):
  File "/home/martin/chart_ws/visualize_charts.py", line 9, in <module>
    enc = seacharts.ENC(size = size, center= center, files = files, new_data = True)
  File "/home/martin/anaconda3/lib/python3.9/site-packages/seacharts/seacharts.py", line 51, in __init__
    self._environment = env.Environment(
  File "/home/martin/anaconda3/lib/python3.9/site-packages/seacharts/environment/environment.py", line 34, in __init__
    self.topography = spl.Topography(self.scope)
  File "<string>", line 3, in __init__
  File "/home/martin/anaconda3/lib/python3.9/site-packages/seacharts/spatial/hypsometry.py", line 113, in __post_init__
    self.load(scope)
  File "/home/martin/anaconda3/lib/python3.9/site-packages/seacharts/spatial/hypsometry.py", line 42, in load
    records = layer.load_fgdb(scope.parser)
  File "/home/martin/anaconda3/lib/python3.9/site-packages/seacharts/spatial/base.py", line 161, in load_fgdb
    return list(parser.read_fgdb(self.label, self._external_labels, depth))
  File "/home/martin/anaconda3/lib/python3.9/site-packages/seacharts/data/parser.py", line 18, in read_fgdb
    yield from self._parse_records(records, label)
  File "/home/martin/anaconda3/lib/python3.9/site-packages/seacharts/data/parser.py", line 45, in _parse_records
    for i, record in enumerate(records):
  File "/home/martin/anaconda3/lib/python3.9/site-packages/seacharts/data/parser.py", line 34, in _parse_layers
    yield from self._read_spatial_file(file_path, layer=label)
  File "/home/martin/anaconda3/lib/python3.9/site-packages/seacharts/data/parser.py", line 37, in _read_spatial_file
    with fiona.open(file_path, 'r', **kwargs) as source:
  File "/home/martin/anaconda3/lib/python3.9/site-packages/fiona/env.py", line 417, in wrapper
    return f(*args, **kwargs)
  File "/home/martin/anaconda3/lib/python3.9/site-packages/fiona/__init__.py", line 264, in open
    c = Collection(path, mode, driver=driver, encoding=encoding,
  File "/home/martin/anaconda3/lib/python3.9/site-packages/fiona/collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 553, in fiona.ogrext.Session.start
ValueError: Null layer: 'ikkekartlagtsjomaltomr'
```

Why is this error ocurring? 

I try running seacharts.ENC( new_data = False) to work with the files already written, but then I get the following error:

```
free(): invalid size
Aborted (core dumped)
```

How can I get past this hurdle?
Thank you!

**Comment by MasHyke** [comment]
I also tried the example with "More_og_romsdal" county and following the usage guide to the point, and I get the following error:
```
Processing 45 km^2 of Hydrography features from: Basisdata_15_More_og_Romsdal_25833_Dybdedata_FGDB.gdb
Saved 1143 Seabed0m geometries to shapefile in 0.8 seconds.
Saved 688 Seabed5m geometries to shapefile in 0.5 seconds.
Saved 478 Seabed10m geometries to shapefile in 0.5 seconds.
Saved 158 Seabed20m geometries to shapefile in 0.3 seconds.
Saved 35 Seabed50m geometries to shapefile in 0.1 seconds.
Saved 13 Seabed100m geometries to shapefile in 0.1 seconds.
Found 0 Seabed200m geometries.

Processing 45 km^2 of Topography features from: Basisdata_15_More_og_Romsdal_25833_Dybdedata_FGDB.gdb
Saved 266 Land geometries to shapefile in 0.4 seconds.
Saved 649 Shore geometries to shapefile in 0.5 seconds.

free(): invalid size
Aborted (core dumped)
```

Ubuntu 20.04
Python 3.9.7
Fiona 1.8.21
Cartopy 0.19.0.post1
Shapely 1.8.1

@simbli

**Comment by simbli** [comment]
> Hi, I am trying to follow your usage recipe on the README, but with a different map from a different county. 
>   File "/home/martin/anaconda3/lib/python3.9/site-packages/fiona/collection.py", line 162, in __init__
>     self.session.start(self, **kwargs)
>   File "fiona/ogrext.pyx", line 553, in fiona.ogrext.Session.start
> ValueError: Null layer: 'ikkekartlagtsjomaltomr'
> 
> Why is this error ocurring?

Thank you very much for reporting this error, it is truly helpful! The error message seems to indicate that the polygon layer roughly translated to "unmapped areas" (ikkekartlagtsjomaltomr) is not actually present in your specified county data set. I'm assuming it is the Fredrikstad data set, EUREF89 UTM sone 33, 2d?

Perhaps it is possible to alternatively circumvent the error simply by removing the string 'ikkekartlagtsjomaltomr' from the Shore class located in **seacharts/spatial/layers.py**. Making this change in the source code resolved this error for me, and the data set generated this image:

![Fredrikstad](https://user-images.githubusercontent.com/10545078/154511327-914179a9-e39e-4413-87ce-d2cd5635fb2a.png)

Let me know if this does not work for you.


> free(): invalid size
> Aborted (core dumped)

Regarding the last part, I'm afraid I've yet to encounter this error as well. I'm running Windows at the moment, let me know if you still encounter this error after firstly resolving the previous error. Try deleting the **data/shapefiles** folder generated from the erroneous previous run related to 'ikkekartlagtsjomaltomr' and rerunning with **new_data=True**, to be safe.

**Comment by MasHyke** [comment]
Hi again,
Thank you very much for your response. Now after deleting "ikkekartlagtsjomaltomr" as instructed, I am not getting that error. Now I am getting the core dumped error instead:
```
Processing 45 km^2 of Hydrography features from: Basisdata_3004_Fredrikstad_25833_Dybdedata_FGDB.gdb
Saved 341 Seabed0m geometries to shapefile in 0.5 seconds.
Saved 99 Seabed5m geometries to shapefile in 0.2 seconds.
Saved 63 Seabed10m geometries to shapefile in 0.1 seconds.
Saved 12 Seabed20m geometries to shapefile in 0.0 seconds.
Found 0 Seabed50m geometries.

Processing 45 km^2 of Topography features from: Basisdata_3004_Fredrikstad_25833_Dybdedata_FGDB.gdb
Saved 57 Land geometries to shapefile in 0.2 seconds.
Saved 245 Shore geometries to shapefile in 0.4 seconds.

free(): invalid size
Aborted (core dumped)
```
Maybe this is an error with some of the sublibraries used by Seacharts?

I tried to run this on Windows10 using Anaconda + Pycharm as well, and I got the following error:
```
C:\Users\Martin\anaconda3\envs\pythonProject\python.exe C:/Users/Martin/PycharmProjects/pythonProject/main.py
Processing 45 km^2 of Hydrography features from: Basisdata_3004_Fredrikstad_25833_Dybdedata_FGDB.gdb
Saved 341 Seabed0m geometries to shapefile in 0.9 seconds.
Saved 99 Seabed5m geometries to shapefile in 0.4 seconds.
Saved 63 Seabed10m geometries to shapefile in 0.3 seconds.
Saved 12 Seabed20m geometries to shapefile in 0.1 seconds.
Found 0 Seabed50m geometries.

Processing 45 km^2 of Topography features from: Basisdata_3004_Fredrikstad_25833_Dybdedata_FGDB.gdb
Saved 57 Land geometries to shapefile in 0.5 seconds.
Saved 245 Shore geometries to shapefile in 0.8 seconds.

Traceback (most recent call last):
  File "C:\Users\Martin\PycharmProjects\pythonProject\main.py", line 9, in <module>
    enc = seacharts.ENC(size=size, center=center, files=files, new_data=True)
  File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\site-packages\seacharts\seacharts.py", line 58, in __init__
    self._display = dis.Display(self._environment)
  File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\site-packages\seacharts\display\display.py", line 41, in __init__
    self.events = EventsManager(self)
  File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\site-packages\seacharts\display\events.py", line 25, in __init__
    self._remove_default_keybindings()
  File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\site-packages\seacharts\display\events.py", line 237, in _remove_default_keybindings
    dic['keymap.all_axes'].remove('a')
  File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\site-packages\matplotlib\__init__.py", line 674, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'keymap.all_axes'

Process finished with exit code 1
```

**Comment by simbli** [comment]
> Hi again, Thank you very much for your response. Now after deleting "ikkekartlagtsjomaltomr" as instructed, I am not getting that error. Now I am getting the core dumped error instead:
> 
> Maybe this is an error with some of the sublibraries used by Seacharts?

Indeed, it seems like the (rather unhelpful) error message stems from some underlying C++ base, possibly within the Fiona or GDAL packages. I'm unable to recreate the error at least on setup, may I have the exact coordinates (origin/center and size) you provide to the ENC initialization?


>   File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\site-packages\seacharts\display\events.py", line 237, in _remove_default_keybindings
>     dic['keymap.all_axes'].remove('a')
>   File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\site-packages\matplotlib\__init__.py", line 674, in __getitem__
>     return dict.__getitem__(self, key)
> KeyError: 'keymap.all_axes'
> 
> Process finished with exit code 1
> ```

This is some mismatch between Matplotlib versions and/or backend which appeared sometime during development, fortunately also with an easy quick fix: Simply comment out the offending line 237 (**dic['keymap.all_axes'].remove('a')**)  in **seacharts\display\events.py**.

Bug fixes for the first problem you brought forward and this latter one will be added to the next minor update. I'm not sure how to handle the "core dumped" issue yet.

**Comment by MasHyke** [comment]
Hi again,

**Linux**:
I finally got it to work on linux. Changes in Seacharts:
 - Removed the string 'ikkekartlagtsjomaltomr' from the Shore class located in seacharts/spatial/layers.py
 - Commented out line 237 (dic['keymap.all_axes'].remove('a')) in seacharts\display\events.py
 
 The combination of versions and packages that worked for me in the end:
  - Ubuntu 20.04
  - Conda 4.11.0
  - Python 3.9.7
  - Fiona 1.8.21
  - Shapely 1.7.1
  - Cartopy 0.18.0
  - Matplotlib 3.5.0

**Windows**:
I didn't get it to work on Windows. I am using Linux as my primary OS, so I won't spend more time debugging this, but I am posting my latest error message in case it is useful for anyone. 

```
C:\Users\Martin\anaconda3\envs\pythonProject\python.exe C:/Users/Martin/PycharmProjects/chart_proj/main.py
Processing 1 km^2 of Hydrography features from: Basisdata_3004_Fredrikstad_25833_Dybdedata_FGDB.gdb
Saved 50 Seabed0m geometries to shapefile in 0.4 seconds.
Saved 7 Seabed5m geometries to shapefile in 0.2 seconds.
Saved 5 Seabed10m geometries to shapefile in 0.2 seconds.
Found 0 Seabed20m geometries.

Processing 1 km^2 of Topography features from: Basisdata_3004_Fredrikstad_25833_Dybdedata_FGDB.gdb
Saved 10 Land geometries to shapefile in 0.2 seconds.
Saved 27 Shore geometries to shapefile in 0.3 seconds.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\site-packages\seacharts\display\display.py", line 39, in __init__
    self.figure, self.sizes, self.spacing, widths = self._init_figure()
  File "C:\Users\Martin\anaconda3\envs\pythonProject\lib\site-packages\seacharts\display\display.py", line 91, in _init_figure
    figure.canvas.toolbar.pack_forget()
AttributeError: 'NoneType' object has no attribute 'pack_forget'

```

Versions:
 - Windows 10 Business 21H1
 - Conda 4.10.3
 - Python 3.9.7
 - Fiona 1.8.13.pos1
 - Shapely 1.7.1
 - Cartopy 0.18.0
 - Matplotlib 3.5.1
